server:
    port: 8085
spring:
    datasource:
        password: ak111patel
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
springpayroll:
    rabbitmq:
        exchange: springpayroll.exchange
        queue: springpayroll.queue
        routingkey: springpayroll.routingkey
